<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class XII_PPLG_3 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Data pengguna dari kelas XII PPLG 3 (berdasarkan file Excel/CSV)
        $data = [
            [
                'name' => 'ADITYA PERMANA RAMADHAN',
                'kelas' => 'XII PPLG 3',
                'email' => 'adityapermanaramadhan@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0046',
            ],
            [
                'name' => 'AL MUTAKIN',
                'kelas' => 'XII PPLG 3',
                'email' => 'almutakin_1@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0164',
            ],
            [
                'name' => 'ALFIHRA PUTRI SYAHBANIA',
                'kelas' => 'XII PPLG 3',
                'email' => 'alfihraputrisyahbania@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0268',
            ],
            [
                'name' => 'ANGGA SAPUTRA',
                'kelas' => 'XII PPLG 3',
                'email' => 'anggasaputra_1@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0077',
            ],
            [
                'name' => 'ARIFIN ILHAM HANAFI',
                'kelas' => 'XII PPLG 3',
                'email' => 'arifinilhamhanafi@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0120',
            ],
            [
                'name' => 'AULIA LESTARI',
                'kelas' => 'XII PPLG 3',
                'email' => 'aulialestari_1@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0345',
            ],
            [
                'name' => 'DAFINA NURUL OKTAVIANI',
                'kelas' => 'XII PPLG 3',
                'email' => 'dafinanuruloktaviani@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0106',
            ],
            [
                'name' => 'HAIFA SYAHLA NUR SABRINA',
                'kelas' => 'XII PPLG 3',
                'email' => 'haifasyahlanursabrina@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0348',
            ],
            [
                'name' => 'MOCH MALIKUL MULKI',
                'kelas' => 'XII PPLG 3',
                'email' => 'mochmalikulmulki@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0218',
            ],
            [
                'name' => 'MUHAMAD ADITYA PRAYOGA',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhamadadityaprayoga@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0315',
            ],
            [
                'name' => 'MUHAMAD AIDIL ADHA',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhamadaidiladha@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0088',
            ],
            [
                'name' => 'MUHAMAD MARIO',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhamadmario_1@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0249',
            ],
            [
                'name' => 'MUHAMAD RAIHAN HADINATA',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhamadraihanhadinata@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0181',
            ],
            [
                'name' => 'MUHAMAD RIZIQ IBRAHIM MUSA',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhamadriziqibrahimmusa@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0227',
            ],
            [
                'name' => 'MUHAMMAD ARDHAN SHIDDIQ',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhammadardhanshiddiq@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0378',
            ],
            [
                'name' => 'MUHAMMAD FAHRI NUR ROBBI',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhammadfahrinurrobbi@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0250',
            ],
            [
                'name' => 'MUHAMMAD FAKHRI MUBAROK',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhammadfakhrimubarok@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0259',
            ],
            [
                'name' => 'MUHAMMAD FIRZA NAJMUDIN PUTRA RAIS',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhammadfirzanajmudinputrarais@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0303',
            ],
            [
                'name' => 'MUHAMMAD RIZAL NASUTION',
                'kelas' => 'XII PPLG 3',
                'email' => 'muhammadrizalnasution@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0379',
            ],
            [
                'name' => 'NAUFAL ABDUL HAKIM BAWAZIER',
                'kelas' => 'XII PPLG 3',
                'email' => 'naufalabdulhakimbawazier@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0383',
            ],
            [
                'name' => 'NAUFAL KHAERUL ANWAR',
                'kelas' => 'XII PPLG 3',
                'email' => 'naufalaziz_1@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0095',
            ],
            [
                'name' => 'NISWATUL HASANAH',
                'kelas' => 'XII PPLG 3',
                'email' => 'nazirahapsariislamiyah@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0325',
            ],
            [
                'name' => 'RAIHAN SAMI',
                'kelas' => 'XII PPLG 3',
                'email' => 'raihansami@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0147',
            ],
            [
                'name' => 'REZA HADI PUTRA',
                'kelas' => 'XII PPLG 3',
                'email' => 'rezahadiputra@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0363',
            ],
            [
                'name' => 'RIZAL GANTENG',
                'kelas' => 'XII PPLG 3',
                'email' => 'rizalabdurahman@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0111',
            ],
            [
                'name' => 'ROBY MARDIANSYAH',
                'kelas' => 'XII PPLG 3',
                'email' => 'robymardiansyah@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0313',
            ],
            [
                'name' => 'SANDI',
                'kelas' => 'XII PPLG 3',
                'email' => 'sandixii@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0062',
            ],
            [
                'name' => 'SHILA ISMA AULIA',
                'kelas' => 'XII PPLG 3',
                'email' => 'shilaismaaulia@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0169',
            ],
            [
                'name' => 'SITI SAHARA KHAERUNNISA',
                'kelas' => 'XII PPLG 3',
                'email' => 'sitisaharakhaerunnisa@gmail.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'sekolah' => 'A1',
                'nis' => '23.5.0063',
            ],
        ];

        // Looping untuk membuat setiap record User
        foreach ($data as $user) {
            User::create($user);
        }
    }
}